annotations:
  artifacthub.io/changes: |-
    - description: 'helm: remove -metrics-secure flag in proxy'
      kind: fixed
      links:
      - name: GitHub commit
        url: https://github.com/enix/kube-image-keeper/commit/a9cc632b898baec4c04b0fac20fc435011c528a1
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Chart Sources
      url: https://github.com/enix/kube-image-keeper/tree/main/helm/kube-image-keeper
    - name: Helm Repository
      url: https://charts.enix.io
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: 1.13.1
dependencies:
  - condition: minio.enabled
    name: minio
    repository: https://charts.bitnami.com/bitnami
    version: 13.2.0
  - condition: docker-registry-ui.enabled
    name: docker-registry-ui
    repository: https://helm.joxit.dev
    version: 1.1.3
description: kuik is a container image caching system for Kubernetes.
home: https://github.com/enix/kube-image-keeper
maintainers:
  - email: contact@enix.fr
    name: Enix
    url: https://github.com/enixsas
  - email: paul.laffitte@enix.fr
    name: Paul Laffitte
    url: https://github.com/paullaffitte
  - email: david.donchez@enix.fr
    name: David Donchez
    url: https://github.com/donch
name: kube-image-keeper
sources:
  - https://github.com/enix/kube-image-keeper
type: application
version: 1.13.1
